# Generated by Django 2.2.4 on 2019-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_readenbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discussed',
            field=models.BooleanField(default=False),
        ),
    ]
